<a href="https://colab.research.google.com/github/akankshakusf/Deep-Learning-Projects/blob/master/2_Linear_Algebra_in_Tensorflow_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf


# 1. tf.linalg.matmul method - matrix multiplication

#### matmul of 2D tensors

In [ ]:
# https://www.tensorflow.org/api_docs/python/tf/linalg/matmul

In [ ]:
a= tf.constant([
  [1,5,1],
  [7,3,0],

])
b = tf.constant([
  [3,1,9],
  [0,1,7],
  [1,5,1]

])
print(a.shape, b.shape) # column of first matrix should be of same size as row of 2nd matrix
print(tf.linalg.matmul(a,b))

(2, 3) (3, 3)
tf.Tensor(
[[ 4 11 45]
 [21 10 84]], shape=(2, 3), dtype=int32)


In [ ]:
a@b

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4, 11, 45],
       [21, 10, 84]], dtype=int32)>

In [ ]:
a= tf.constant([
  [3,1,9,6,5],
  [0,1,7,3,2],
  [1,5,1,2,0],
  [7,3,0,9,0],

])
b = tf.constant([
  [3,1,9,6,5],
  [0,1,7,3,2],
  [1,5,1,2,0],
  [7,3,0,9,0],
  [7,3,0,9,0],

])
print(a.shape, b.shape) # column of first matrix should be of same size as row of 2nd matrix
print(tf.linalg.matmul(a,b))

(4, 5) (5, 5)
tf.Tensor(
[[ 95  82  43 138  17]
 [ 42  51  14  62   2]
 [ 18  17  45  41  15]
 [ 84  37  84 132  41]], shape=(4, 5), dtype=int32)


In [ ]:
#transpose
a= tf.constant([
  [1,5,1],
  [7,3,0],

])
print(tf.transpose(a))

tf.Tensor(
[[1 7]
 [5 3]
 [1 0]], shape=(3, 2), dtype=int32)


In [ ]:
a = tf.constant([
  [1,5,1],

])
print(a.shape,tf.transpose(a))

b = tf.constant([
  [3,1,9],
  [0,1,7],
  [1,5,1]

])

print(tf.linalg.matmul(a,b))

(1, 3) tf.Tensor(
[[1]
 [5]
 [1]], shape=(3, 1), dtype=int32)
tf.Tensor([[ 4 11 45]], shape=(1, 3), dtype=int32)


In [ ]:
#multiply a by b
a@b

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[ 4, 11, 45]], dtype=int32)>

In [ ]:
#multiply a by b but take transpose of b
a@tf.transpose(b)

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[17, 12, 27]], dtype=int32)>

In [ ]:
#different way of doing the same thing
tf.linalg.matmul(a,b,transpose_b= True)

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[17, 12, 27]], dtype=int32)>

* this mat mul worked cause the a, b shapes where compatible but in below example see that this matmul fails if columns of "a" not match rows of "b"
* Understand that if you are simple multiple and it works if can still fail if you take transpose of one of the matrix and the Matrix size-incompatible issue arises

In [ ]:
# this is to show ISSUE - Matrix size-incompatible ERROR :
a = tf.constant([
  [1,5,1],

])
b = tf.constant([
  [3,1,9],
  [0,1,7],

])
print(a.shape,b.shape)
print(tf.linalg.matmul(a,b))


(1, 3) (2, 3)


InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [1,3], In[1]: [2,3] [Op:MatMul] name: 

In [ ]:
a = tf.constant([
  [1,5,1],
])

b = tf.constant([
  [3,1],
  [0,1],
  [1,5],
])

print(a.shape, b.shape, tf.linalg.matrix_transpose(b).shape)
a@b

(1, 3) (3, 2) (2, 3)


<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[ 4, 11]], dtype=int32)>

#### matmul of 3D tensors

In [ ]:
a = tf.constant(
            [[[1,2],
              [3,5]],

            [[10,2],
              [1,0]],

            [[5,8],
              [2,7]],

            [[2,1],
              [4,-3]]])


b = tf.constant(
            [[[1,2,0],
              [3,5,-1]],

            [[10,2,0],
              [1,0,2]],

            [[5,8,0],
              [2,7,0]],

            [[2,1,9],
              [4,-3,32]]])
print(a.shape, b.shape)

(4, 2, 2) (4, 2, 3)


* Great !! this will  work matrix a= column shape(2) and matrix b=row shape(2)

In [ ]:
print(tf.linalg.matmul(a,b))

tf.Tensor(
[[[  7  12  -2]
  [ 18  31  -5]]

 [[102  20   4]
  [ 10   2   0]]

 [[ 41  96   0]
  [ 24  65   0]]

 [[  8  -1  50]
  [ -4  13 -60]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
print(a[0],b[0])

tf.Tensor(
[[1 2]
 [3 5]], shape=(2, 2), dtype=int32) tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)


In [ ]:
a[0]@b[0]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7, 12, -2],
       [18, 31, -5]], dtype=int32)>

In [ ]:
a[2]@b[2]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[41, 96,  0],
       [24, 65,  0]], dtype=int32)>

# 2. tf.linalg.band_part method

In [ ]:
a = tf.constant([
  [1,5,1],
  [7,9,3],
  [1,3,1],
])


In [ ]:
# substitute and understand
output = tf.linalg.band_part(a, m, n)
output = tf.linalg.band_part(a, 0, 0)

# this is explaination for (a, m, n): (a, 0,0): meaning 0th row-0th column =1
m=0, n=0  m-n=-1 n-m=0
      False              True                   False              True
              True                                      True
                                   True
(num_lower < 0 || (m-n) <= num_lower)) && (num_upper < 0 || (n-m) <= num_upper).

# this is explaination for (a, m, n): (a, 0,1) : meaning 0th row-1th column = 5

m=0, n=1  m-n=-1 n-m=1
      False              True                   False              True
              True                                      True
                                   True
(num_lower < 0 || (m-n) <= num_lower)) && (num_upper < 0 || (n-m) <= num_upper).
                      (0<0 ||-1 <= 0) && (1<0 || 1<=1)

                      # this is explaination for (a, m, n): (a, 0,-1) : meaning 0th row-1th column = 5

m=0, n=-1  m-n=1 n-m=-1
      False              False                   True              True
              False                                      True
                                   False
(num_lower < 0 || (m-n) <= num_lower)) && (num_upper < 0 || (n-m) <= num_upper).
                      (0<0 ||1 <= 0) && (-1<0 || -1<=-1)

In [ ]:
print(a)
print(tf.linalg.band_part(a, 0,0))
print(tf.linalg.band_part(a, 0,1))
print(tf.linalg.band_part(a, 0,-1))


tf.Tensor(
[[1 5 1]
 [7 9 3]
 [1 3 1]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 0 0]
 [0 9 0]
 [0 0 1]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 5 0]
 [0 9 3]
 [0 0 1]], shape=(3, 3), dtype=int32)


In [ ]:
a = tf.constant([
    [2,6,5,2],
    [2,-2,2,3],
    [1,5,4,0]
])
b = tf.constant([
    [2,9,0,3,0],
    [3,6,8,-2,2],
    [1,3,5,0,1],
    [3,0,2,0,5]
])
c = tf.linalg.matmul(a,b)
print(a.shape,b.shape)
print(c.shape)
print(c)

(3, 4) (4, 5)
(3, 5)
tf.Tensor(
[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]], shape=(3, 5), dtype=int32)


# tf.einsum

In [ ]:
a = tf.constant([
    [2,6,5,2],
    [2,-2,2,3],
    [1,5,4,0]
])
b = tf.constant([
    [2,9,0,3,0],
    [3,6,8,-2,2],
    [1,3,5,0,1],
    [3,0,2,0,5]
])
c = tf.linalg.matmul(a,b)
print(a.shape,b.shape)
print(c.shape)
print(c)

(3, 4) (4, 5)
(3, 5)
tf.Tensor(
[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]], shape=(3, 5), dtype=int32)


In [ ]:
tf.einsum("ij,jk->ik",a,b)

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[33, 69, 77, -6, 27],
       [ 9, 12,  0, 10, 13],
       [21, 51, 60, -7, 14]], dtype=int32)>

In [ ]:
a = tf.constant([2,6,5,2])
b = tf.constant([0,1,3,2])
tf.einsum("i,j->",a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=90>

In [ ]:
a = tf.constant([2,6,5,2])
b = tf.constant([0,1,3,2])
c = tf.einsum("i,j->ij",a,b)
print(c)
print(tf.reduce_sum(c))

print(tf.einsum("i,j->",a,b))

tf.Tensor(
[[ 0  2  6  4]
 [ 0  6 18 12]
 [ 0  5 15 10]
 [ 0  2  6  4]], shape=(4, 4), dtype=int32)
tf.Tensor(90, shape=(), dtype=int32)
tf.Tensor(90, shape=(), dtype=int32)


In [ ]:
b = tf.constant([
    [2,9,0,3,0],
    [3,6,8,-2,2],
    [1,3,5,0,1],
    [3,0,2,0,5]
])
tf.einsum("ij->ji",b)

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[ 2,  3,  1,  3],
       [ 9,  6,  3,  0],
       [ 0,  8,  5,  2],
       [ 3, -2,  0,  0],
       [ 0,  2,  1,  5]], dtype=int32)>

In [ ]:
a = tf.constant([
    [2,6,5,2],
    [2,-2,2,3],
    [1,5,4,0]
])
b = tf.constant([
    [2,9,0,3],
    [3,6,8,-2],
    [1,3,5,0],
])
tf.einsum("ij,ij->ij",a,b)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[  4,  54,   0,   6],
       [  6, -12,  16,  -6],
       [  1,  15,  20,   0]], dtype=int32)>

In [ ]:
a = tf.constant([

    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,0]],

    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,0]]
    ])
b = tf.constant([
    [[2,9,0,3,0],
     [3,6,8,-2,2],
     [1,3,5,0,1],
     [3,0,2,0,5]],

    [[2,9,0,3,0],
     [3,6,8,-2,2],
     [1,3,5,0,1],
     [3,0,2,0,5]]
])

In [43]:
tf.einsum("bij,bjk->bik",a,b)

<tf.Tensor: shape=(2, 3, 5), dtype=int32, numpy=
array([[[33, 69, 77, -6, 27],
        [ 9, 12,  0, 10, 13],
        [21, 51, 60, -7, 14]],

       [[33, 69, 77, -6, 27],
        [ 9, 12,  0, 10, 13],
        [21, 51, 60, -7, 14]]], dtype=int32)>