<a href="https://colab.research.google.com/github/akankshakusf/Deep-Learning-Projects/blob/master/3.TensorCommonMethods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import tensorflow as tf

# 1.tf.expand_dims
* Returns a tensor with a length 1 axis inserted at index axis.

#### 1D tensors

In [4]:
input=tf.constant([1,3,4,5,6,7])
print(input.shape)

(6,)


In [5]:
tf.expand_dims(input,axis =0)

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 3, 4, 5, 6, 7]], dtype=int32)>

In [6]:
tf.expand_dims(input,axis =1)

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1],
       [3],
       [4],
       [5],
       [6],
       [7]], dtype=int32)>

#### 2D tensors

In [8]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6]], dtype = tf.float32)
tensor_two_d.shape

TensorShape([3, 3])

In [9]:
tf.expand_dims(tensor_two_d,axis=0)

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[  1.,  -2.,   0.],
        [  3.,   5., 100.],
        [  1.,   5.,   6.]]], dtype=float32)>

#### 3D tensors

In [11]:
tensor_three_d = tf.constant([[[1,2,0],
                             [3,5,-1]],

                            [[10,2,0],
                             [1,0,2]],

                            [[5,8,0],
                             [2,7,0]],

                            [[2,1,9],
                             [4,-3,32]]])

tf.expand_dims(tensor_three_d,axis=0).shape.as_list() #You can add an outer batch axis by passing axis=0:

[1, 4, 2, 3]

In [12]:
image = tf.zeros([10,10,3])
tf.expand_dims(image, -1).shape.as_list() # 1 is added at the end

[10, 10, 3, 1]

# 2.tf.squeeze  # this is opposite of expand dimensions

In [18]:
a= tf.constant([

    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,0]],

    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,0]]
    ])

print(a.shape)

(2, 3, 4)


In [22]:
c= tf.expand_dims(a,axis=-1) # 1 dimension is added
print(c.shape)
print(tf.squeeze(c,axis=-1))

(2, 3, 4, 1)
tf.Tensor(
[[[ 2  6  5  2]
  [ 2 -2  2  3]
  [ 1  5  4  0]]

 [[ 2  6  5  2]
  [ 2 -2  2  3]
  [ 1  5  4  0]]], shape=(2, 3, 4), dtype=int32)


# 3.tf.reshape

In [26]:
#since i have 9 values in my tensor i have asked that to be changed to 3,3
a=tf.constant([1,2,3,4,5,6,7,8,9])
print(a.shape)
print(tf.reshape(a,[3,3]))

(9,)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [27]:
# we can also make 3,3,1
a=tf.constant([1,2,3,4,5,6,7,8,9])
print(a.shape)
print(tf.reshape(a,[3,3,1]))

(9,)
tf.Tensor(
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]], shape=(3, 3, 1), dtype=int32)


In [28]:
#lets say you are confusedand dnt know what to write
#just write 3,-1 and tensorflow will figure out how to make the matrix
a=tf.constant([1,2,3,4,5,6,7,8,9])
print(a.shape)
print(tf.reshape(a,[3,-1])) #tensorflow will figure out how to make the matrix

(9,)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [29]:
#if you want to reshape this outcome now to 3,3,1
print(tf.reshape(a,[3,-1,1]))

tf.Tensor(
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]], shape=(3, 3, 1), dtype=int32)


In [33]:
t1 = tf.constant([[1, 2, 3],
      [4, 5, 6]])

print(t1.shape)

(2, 3)


In [41]:
# we reshape t1 : 2ways
print(tf.reshape(t1,[6]) )
print(tf.reshape(t1,[3,2]))


tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


# 4.tf.concat
* Concatenates tensors along one dimension.

In [43]:
t1 = tf.constant([[1, 2, 3],
      [4, 5, 6]])
t2 = tf.constant([[7, 8, 9],
      [10, 11, 12]])
print(t1.shape,t2.shape)

(2, 3) (2, 3)


In [44]:
tf.concat([t1,t2],axis =0) # puts row wise

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [45]:
tf.concat([t1,t2],axis =1) # puts column wise

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]], dtype=int32)>

In [46]:
t1 =tf.constant([
      [[1, 2],
       [2, 3]],

       [[4, 4],
        [5, 3]]
      ])
t2 = tf.constant([
    [[7, 4],
       [8, 4]],

       [[2, 10],
        [15, 11]]
    ])
print(t1.shape,t2.shape)

(2, 2, 2) (2, 2, 2)


In [47]:
print(tf.concat([t1,t2],-1))

tf.Tensor(
[[[ 1  2  7  4]
  [ 2  3  8  4]]

 [[ 4  4  2 10]
  [ 5  3 15 11]]], shape=(2, 2, 4), dtype=int32)


In [48]:
print(tf.concat([t1,t2],0))

tf.Tensor(
[[[ 1  2]
  [ 2  3]]

 [[ 4  4]
  [ 5  3]]

 [[ 7  4]
  [ 8  4]]

 [[ 2 10]
  [15 11]]], shape=(4, 2, 2), dtype=int32)
