<a href="https://colab.research.google.com/github/akankshakusf/Deep-Learning-Projects/blob/master/3.TensorCommonMethods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import tensorflow as tf

# 1.tf.expand_dims
* Returns a tensor with a length 1 axis inserted at index axis.

#### 1D tensors

In [4]:
# https://www.tensorflow.org/api_docs/python/tf/expand_dims
input=tf.constant([1,3,4,5,6,7])
print(input.shape)

(6,)


In [5]:
tf.expand_dims(input,axis =0)

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 3, 4, 5, 6, 7]], dtype=int32)>

In [6]:
tf.expand_dims(input,axis =1)

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1],
       [3],
       [4],
       [5],
       [6],
       [7]], dtype=int32)>

#### 2D tensors

In [8]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6]], dtype = tf.float32)
tensor_two_d.shape

TensorShape([3, 3])

In [9]:
tf.expand_dims(tensor_two_d,axis=0)

<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[  1.,  -2.,   0.],
        [  3.,   5., 100.],
        [  1.,   5.,   6.]]], dtype=float32)>

#### 3D tensors

In [11]:
tensor_three_d = tf.constant([[[1,2,0],
                             [3,5,-1]],

                            [[10,2,0],
                             [1,0,2]],

                            [[5,8,0],
                             [2,7,0]],

                            [[2,1,9],
                             [4,-3,32]]])

tf.expand_dims(tensor_three_d,axis=0).shape.as_list() #You can add an outer batch axis by passing axis=0:

[1, 4, 2, 3]

In [12]:
image = tf.zeros([10,10,3])
tf.expand_dims(image, -1).shape.as_list() # 1 is added at the end

[10, 10, 3, 1]

# 2.tf.squeeze  # this is opposite of expand dimensions

In [18]:
# https://www.tensorflow.org/api_docs/python/tf/squeeze
a= tf.constant([

    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,0]],

    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,0]]
    ])

print(a.shape)

(2, 3, 4)


In [22]:
c= tf.expand_dims(a,axis=-1) # 1 dimension is added
print(c.shape)
print(tf.squeeze(c,axis=-1))

(2, 3, 4, 1)
tf.Tensor(
[[[ 2  6  5  2]
  [ 2 -2  2  3]
  [ 1  5  4  0]]

 [[ 2  6  5  2]
  [ 2 -2  2  3]
  [ 1  5  4  0]]], shape=(2, 3, 4), dtype=int32)


# 3.tf.reshape

In [26]:
# https://www.tensorflow.org/api_docs/python/tf/reshape
#since i have 9 values in my tensor i have asked that to be changed to 3,3
a=tf.constant([1,2,3,4,5,6,7,8,9])
print(a.shape)
print(tf.reshape(a,[3,3]))

(9,)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [27]:
# we can also make 3,3,1
a=tf.constant([1,2,3,4,5,6,7,8,9])
print(a.shape)
print(tf.reshape(a,[3,3,1]))

(9,)
tf.Tensor(
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]], shape=(3, 3, 1), dtype=int32)


In [28]:
#lets say you are confusedand dnt know what to write
#just write 3,-1 and tensorflow will figure out how to make the matrix
a=tf.constant([1,2,3,4,5,6,7,8,9])
print(a.shape)
print(tf.reshape(a,[3,-1])) #tensorflow will figure out how to make the matrix

(9,)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [29]:
#if you want to reshape this outcome now to 3,3,1
print(tf.reshape(a,[3,-1,1]))

tf.Tensor(
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]], shape=(3, 3, 1), dtype=int32)


In [33]:
t1 = tf.constant([[1, 2, 3],
      [4, 5, 6]])

print(t1.shape)

(2, 3)


In [41]:
# we reshape t1 : 2ways
print(tf.reshape(t1,[6]) )
print(tf.reshape(t1,[3,2]))


tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


# 4.tf.concat
* Concatenates tensors along one dimension.

In [43]:
# https://www.tensorflow.org/api_docs/python/tf/constant
t1 = tf.constant([[1, 2, 3],
      [4, 5, 6]])
t2 = tf.constant([[7, 8, 9],
      [10, 11, 12]])
print(t1.shape,t2.shape)

(2, 3) (2, 3)


In [44]:
tf.concat([t1,t2],axis =0) # puts row wise

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [45]:
tf.concat([t1,t2],axis =1) # puts column wise

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]], dtype=int32)>

In [46]:
t1 =tf.constant([
      [[1, 2],
       [2, 3]],

       [[4, 4],
        [5, 3]]
      ])
t2 = tf.constant([
    [[7, 4],
       [8, 4]],

       [[2, 10],
        [15, 11]]
    ])
print(t1.shape,t2.shape)

(2, 2, 2) (2, 2, 2)


In [47]:
print(tf.concat([t1,t2],-1))

tf.Tensor(
[[[ 1  2  7  4]
  [ 2  3  8  4]]

 [[ 4  4  2 10]
  [ 5  3 15 11]]], shape=(2, 2, 4), dtype=int32)


In [48]:
print(tf.concat([t1,t2],0))

tf.Tensor(
[[[ 1  2]
  [ 2  3]]

 [[ 4  4]
  [ 5  3]]

 [[ 7  4]
  [ 8  4]]

 [[ 2 10]
  [15 11]]], shape=(4, 2, 2), dtype=int32)


# 5.tf.stack
* Stacks a list of rank-R tensors into one rank-(R+1) tensor.

In [55]:
#https://www.tensorflow.org/api_docs/python/tf/stack
t1 =tf.constant([
      [[1, 2],
       [2, 3]],

       [[4, 4],
        [5, 3]]
      ])
t2 = tf.constant([
    [[7, 4],
       [8, 4]],

       [[2, 10],
        [15, 11]]
    ])

print(t1.shape,t2.shape)

(2, 2, 2) (2, 2, 2)


In [56]:
tf.stack([t1,t2], axis =0)

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[ 1,  2],
         [ 2,  3]],

        [[ 4,  4],
         [ 5,  3]]],


       [[[ 7,  4],
         [ 8,  4]],

        [[ 2, 10],
         [15, 11]]]], dtype=int32)>

In [57]:
tf.stack([t1,t2], axis =-1)

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[ 1,  7],
         [ 2,  4]],

        [[ 2,  8],
         [ 3,  4]]],


       [[[ 4,  2],
         [ 4, 10]],

        [[ 5, 15],
         [ 3, 11]]]], dtype=int32)>

# 6.tf.pad

In [58]:
#https://www.tensorflow.org/api_docs/python/tf/pad
t = tf.constant([[1, 2, 3],
                 [4, 5, 6]])
paddings = tf.constant([[1, 1,],
                        [2, 2]])
# 'constant_values' is 0.
# rank of 't' is 2.
print(tf.pad(t, paddings, "CONSTANT"))

tf.Tensor(
[[0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 0 0 0 0 0]], shape=(4, 7), dtype=int32)


In [59]:
t = tf.constant([[1, 2, 3],
                 [4, 5, 6]])
paddings = tf.constant([[1, 1,],
                        [2, 4]])
# 'constant_values' is 0.
# rank of 't' is 2.
print(tf.pad(t, paddings, "CONSTANT"))

tf.Tensor(
[[0 0 0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0 0 0]
 [0 0 4 5 6 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]], shape=(4, 9), dtype=int32)


In [60]:
t = tf.constant([[1, 2, 3],
                 [4, 5, 6]])
paddings = tf.constant([[4, 1,],
                        [2, 4]])
# 'constant_values' is 0.
# rank of 't' is 2.
print(tf.pad(t, paddings, "CONSTANT"))

tf.Tensor(
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0 0 0]
 [0 0 4 5 6 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]], shape=(7, 9), dtype=int32)


In [61]:
t = tf.constant([[1, 2, 3],
                 [4, 5, 6]])
paddings = tf.constant([[1, 1,],
                        [2, 4]])
# 'constant_values' is 0.
# rank of 't' is 2.
print(tf.pad(t, paddings, "CONSTANT", constant_values=9))

tf.Tensor(
[[9 9 9 9 9 9 9 9 9]
 [9 9 1 2 3 9 9 9 9]
 [9 9 4 5 6 9 9 9 9]
 [9 9 9 9 9 9 9 9 9]], shape=(4, 9), dtype=int32)


# 7.tf.gather

In [62]:
# https://www.tensorflow.org/api_docs/python/tf/gather
a=tf.constant([4,5,6,7])
print(a[1:3])

tf.Tensor([5 6], shape=(2,), dtype=int32)


In [63]:
tf.gather(a,[0,3,1], axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 7, 5], dtype=int32)>

In [64]:
b=tf.constant([
    [2,9,0,3,0],
    [3,6,8,-2,2],
    [1,3,5,0,1],
    [3,0,2,0,5],
])

In [66]:
tf.gather(b,[3,0], axis=0) # row wise

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[3, 0, 2, 0, 5],
       [2, 9, 0, 3, 0]], dtype=int32)>

In [69]:
tf.gather(b,[1,3], axis=1) # column wise

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 9,  3],
       [ 6, -2],
       [ 3,  0],
       [ 0,  0]], dtype=int32)>

In [70]:
tf.gather(b,[1,3], axis=0)

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 3,  6,  8, -2,  2],
       [ 3,  0,  2,  0,  5]], dtype=int32)>

In [72]:
tf.gather(b,[[1,3],
          [2,0]], axis=0)

<tf.Tensor: shape=(2, 2, 5), dtype=int32, numpy=
array([[[ 3,  6,  8, -2,  2],
        [ 3,  0,  2,  0,  5]],

       [[ 1,  3,  5,  0,  1],
        [ 2,  9,  0,  3,  0]]], dtype=int32)>

# 8.tf.gather_nd
* tf.gather_nd: An operation similar to tf.gather but gathers across multiple axis at once (it can gather elements of a matrix instead of rows or columns)


In [74]:
b=tf.constant([
    [2,9,0,3,0],
    [3,6,8,-2,2],
    [1,3,5,0,1],
    [3,0,2,0,5],
])

In [75]:
#https://www.tensorflow.org/api_docs/python/tf/gather_nd
tf.gather_nd(b,[[1,3],
          [2,0]])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-2,  1], dtype=int32)>

In [77]:
tf.gather_nd(b,[[1],
          [3]])

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 3,  6,  8, -2,  2],
       [ 3,  0,  2,  0,  5]], dtype=int32)>

# 9.tf.ragged

In [80]:
#https://www.tensorflow.org/api_docs/python/tf/ragged
a=tf.ragged.constant([
    [1,3,],
    [4,5,6],
    [7,]
])
print(a)

<tf.RaggedTensor [[1, 3], [4, 5, 6], [7]]>


# 10.tf.ragged.boolean_mask

In [81]:
##https://www.tensorflow.org/api_docs/python/tf/ragged
# Aliases for True & False so data and mask line up.
T, F = (True, False)
tf.ragged.boolean_mask(  # Mask a 2D RaggedTensor.
    tf.ragged.constant([[1, 2, 3], [4], [5, 6]]),
    tf.ragged.constant([[F, F, T], [F], [T, T]])).to_list() #its takes out elements that are false

[[3], [], [5, 6]]

# 11. tf.RaggedTensor.from_row_limits

In [ ]:
##https://www.tensorflow.org/api_docs/python/tf/ragged
#this is just for explaination of below
list = [3, 1, 4, 1, 5, 9, 2, 6]
         0   1   2   3   4   5   6

In [83]:
values = [3, 1, 4, 1, 5, 9, 2, 6]
print(tf.RaggedTensor.from_row_splits(values, row_splits=[0, 4, 4, 7, 8, 8]))

print(tf.RaggedTensor.from_row_lengths(values, row_lengths=[4, 0, 3, 1, 0]))

print(tf.RaggedTensor.from_value_rowids(
    values, value_rowids=[0, 0, 0, 0, 2, 2, 2, 3], nrows=5))

print(tf.RaggedTensor.from_row_starts(values, row_starts=[0, 4, 4, 7, 8]))

print(tf.RaggedTensor.from_row_limits(values, row_limits=[4, 4, 7, 8, 8]))

print(tf.RaggedTensor.from_uniform_row_length(values, uniform_row_length=2))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>
<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>
<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>
<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>
<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>
<tf.RaggedTensor [[3, 1],
 [4, 1],
 [5, 9],
 [2, 6]]>


# 12.tf.sparse.SparseTensor

In [100]:
#https://www.tensorflow.org/guide/sparse_tensor
sparse_tensor = tf.sparse.SparseTensor(
                     indices=[[0, 0],
                              [2,5]],
                      values=[5, 9],
                 dense_shape=[5,6])

In [101]:
sparse_tensor

SparseTensor(indices=tf.Tensor(
[[0 0]
 [2 5]], shape=(2, 2), dtype=int64), values=tf.Tensor([5 9], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))

In [102]:
tf.sparse.to_dense(sparse_tensor)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)>

# 13.tf.strings.split

In [106]:
#https://www.tensorflow.org/api_docs/python/tf/strings/split
tensor_string=tf.constant(["i am","a","string"])
tensor_string

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'i am', b'a', b'string'], dtype=object)>

# 14.tf.strings.join

In [107]:
# https://www.tensorflow.org/api_docs/python/tf/strings/join
tf.strings.join(tensor_string,separator="+")

<tf.Tensor: shape=(), dtype=string, numpy=b'i am+a+string'>

In [111]:
tensor_string_1=tf.constant(["i am","a","string"])
tensor_string_2=tf.constant(["i am","not a","string"])

In [112]:
tf.strings.join([tensor_string_1,tensor_string_2],separator="+")

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'i am+i am', b'a+not a', b'string+string'], dtype=object)>

# 15. Tensor variable

In [113]:
x= tf.constant([1,2,3,4,5])
x_var= tf.Variable(x)

In [115]:
print(x)
print(x_var)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>


In [118]:
x_var.assign_add([5,5,5,5,5])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([ 6,  7,  8,  9, 10], dtype=int32)>

In [120]:
x_var.assign_sub([5,5,5,5,5])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([-4, -3, -2, -1,  0], dtype=int32)>

In [121]:
x_var.assign([5,5,5,5,5])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([5, 5, 5, 5, 5], dtype=int32)>