<a href="https://colab.research.google.com/github/akankshakusf/Deep-Learning-Projects/blob/master/TensorFlow_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.Type of densional tensors - pay attention to closing brackets
* 1 closing square brackets"[---]" ----> 1D
* 2 closing square brackets"[[---]]" ----> 2D
* 3 closing square brackets"[[[---]]]" ----> 3D
* 4 closing square brackets"[[[[---]]]]" ----> 4D

In [19]:
#import packages
import tensorflow as tf

In [20]:
tensor_zero_d=tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [21]:
#one d
tensor_one_d=tf.constant([2,0,-3, 8 ,90.1])
print(tensor_one_d)

tf.Tensor([ 2.   0.  -3.   8.  90.1], shape=(5,), dtype=float32)


In [22]:
tensor_one_d.shape

TensorShape([5])

In [124]:
#stacked one d is 2 d
tensor_two_d = tf.constant(
    [[1,2,3],
    [3,5,-1],
    [4,5,6],
    [2,3,8]]
    )
print(tensor_two_d)

tf.Tensor(
[[ 1  2  3]
 [ 3  5 -1]
 [ 4  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [24]:
tensor_two_d.shape

TensorShape([4, 3])

In [125]:
#stacked 2 d is 3 d
tensor_three_d=tf.constant(
    [[[1,2,3], # as you see they are stacked
     [4,5,6]],

    [[5,6,4],
     [2,0,6]],

    [[9,2,1],
     [4,9,5]],

    [[1,5,3],
     [0,1,6]],]

)
print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[5 6 4]
  [2 0 6]]

 [[9 2 1]
  [4 9 5]]

 [[1 5 3]
  [0 1 6]]], shape=(4, 2, 3), dtype=int32)


In [26]:
tensor_three_d.shape

TensorShape([4, 2, 3])

In [126]:
#stacked 3 d is 4 d
tensor_four_d=tf.constant(
[[[[1,2,3],
     [4,5,6]],

    [[5,6,4],
     [2,0,6]],

    [[9,3,1],
     [4,0,5]],

    [[1,5,3],
     [0,1,6]]
],  #--------first stack ends here

[    [[1,7,3],
     [4,5,0]],

    [[5,9,4],
     [2,0,6]],

    [[32,2,1],
     [4,9,5]],

    [[1,5,3],
     [0,3,43]]

], #--------second stack ends here

[   [[1,2,3],
     [4,6,6]],

    [[5,6,4],
     [2,2,6]],

    [[9,2,1],
     [4,9,5]],

    [[1,2,3],
     [0,1,9]]],])
#--------third stack ends here

print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 5  6  4]
   [ 2  0  6]]

  [[ 9  3  1]
   [ 4  0  5]]

  [[ 1  5  3]
   [ 0  1  6]]]


 [[[ 1  7  3]
   [ 4  5  0]]

  [[ 5  9  4]
   [ 2  0  6]]

  [[32  2  1]
   [ 4  9  5]]

  [[ 1  5  3]
   [ 0  3 43]]]


 [[[ 1  2  3]
   [ 4  6  6]]

  [[ 5  6  4]
   [ 2  2  6]]

  [[ 9  2  1]
   [ 4  9  5]]

  [[ 1  2  3]
   [ 0  1  9]]]], shape=(3, 4, 2, 3), dtype=int32)


In [28]:
tensor_four_d.shape

TensorShape([3, 4, 2, 3])

# 2. manually changing the data type
* lower precision tensors float 16, float 32, float 64 etc

In [32]:
tensor_one_d=tf.constant([2,0,-3, 8 ,90.1], dtype=tf.float16)
print(tensor_one_d)

tensor_one_d=tf.constant([2,0,-3, 8 ,90.1], dtype=tf.float32)
print(tensor_one_d)

tensor_one_d=tf.constant([2,0,-3, 8 ,90.1], dtype=tf.float64)
print(tensor_one_d)

tf.Tensor([ 2.   0.  -3.   8.  90.1], shape=(5,), dtype=float16)
tf.Tensor([ 2.   0.  -3.   8.  90.1], shape=(5,), dtype=float32)
tf.Tensor([ 2.   0.  -3.   8.  90.1], shape=(5,), dtype=float64)


This is simply means that tensors will take less space in ram

# 3. Casting of tensors to different data types

In [37]:
tensor_one_d=tf.constant([2,0,-3, 8 ,90.1], dtype=tf.float16)

casted_tensor_one_d=tf.cast(tensor_one_d, dtype=tf.int64)
print(casted_tensor_one_d)
print(tensor_one_d)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int64)
tf.Tensor([ 2.   0.  -3.   8.  90.1], shape=(5,), dtype=float16)


In [38]:
tensor_two_d = tf.constant([
    [1,2,3],
    [3,5,-1],
    [4,5,6],
    [2,3,8]
])

casted_tensor_two_d=tf.cast(tensor_two_d, dtype=tf.float32)
print(casted_tensor_two_d)
print(tensor_two_d)

tf.Tensor(
[[ 1.  2.  3.]
 [ 3.  5. -1.]
 [ 4.  5.  6.]
 [ 2.  3.  8.]], shape=(4, 3), dtype=float32)
tf.Tensor(
[[ 1  2  3]
 [ 3  5 -1]
 [ 4  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [40]:
tensor_one_d=tf.constant([2,0,-3, 8 ,90.1], dtype=tf.float16)
print(tensor_one_d)
tensor_bool=tf.cast(tensor_one_d,dtype=tf.bool)
print(tensor_bool)

tf.Tensor([ 2.   0.  -3.   8.  90.1], shape=(5,), dtype=float16)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [41]:
tensor_string=tf.constant(["hello world","hi"])
print(tensor_string)

tf.Tensor([b'hello world' b'hi'], shape=(2,), dtype=string)


# 4. Converting Numpy to tensor

In [43]:
import numpy as np
np_array=np.array([1,2,3])
print(np_array)


[1 2 3]


In [44]:
converted_tensor=tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [45]:
#recheck the type
print(type(np_array))
print(type(converted_tensor))

<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


# 5. Using eye method


In [52]:
# got this code form "https://www.tensorflow.org/api_docs/python/tf/eye"
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float16,
    name=None
)
print(3*eye_tensor)

tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float16)


In [53]:
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.bool,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[ True False False]
 [False  True False]
 [False False  True]], shape=(3, 3), dtype=bool)


In [58]:
# changing batch size
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[3,],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(3, 5, 5), dtype=float32)


In [59]:
# changing batch size
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(2, 5, 5), dtype=float32)


In [60]:
# changing batch size
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,4],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 4, 5, 5), dtype=float32)


# 5. Using Fill method


In [61]:
# https://www.tensorflow.org/api_docs/python/tf/fill
fill_tensor=tf.fill(
    [1,3,4], 5, name=None, layout=None
)
print(fill_tensor) # 3d

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


# 6. Using Ones method  

In [62]:
# https://www.tensorflow.org/api_docs/python/tf/ones
ones_tensor=tf.ones(
    [5,3], #shape 2d
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [63]:
ones_tensor=tf.ones(
    [5,3,2], #shape 3d
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)
print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(5, 3, 2), dtype=float32)


# 7. Using Ones like Method

In [67]:
# https://www.tensorflow.org/api_docs/python/tf/ones_like
once_like_tensor = tf.ones_like(fill_tensor)
print(once_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(1, 3, 4), dtype=int32)


# 8. Using Zeros method

In [68]:
#https://www.tensorflow.org/api_docs/python/tf/zeros
zeros_tensor=tf.zeros(
    [3,2],
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)
print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


# 9. Using shape method

In [73]:
#https://www.tensorflow.org/api_docs/python/tf/shape
print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[5 6 4]
  [2 0 6]]

 [[9 2 1]
  [4 9 5]]

 [[1 5 3]
  [0 1 6]]], shape=(4, 2, 3), dtype=int32)


In [72]:
print(tf.shape(tensor_three_d))

tf.Tensor([4 2 3], shape=(3,), dtype=int32)


# 10.Rank method

In [76]:
# https://www.tensorflow.org/api_docs/python/tf/rank
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[1, 1, 1], [2, 2, 2]])
tf.rank(t)  # 3


<tf.Tensor: shape=(), dtype=int32, numpy=2>

# 11.Size method

In [78]:
#https://www.tensorflow.org/api_docs/python/tf/size
#tf.shape.- Returns a 0-D Tensor representing the number of elements in input of type out_type. Defaults to tf.int32.
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [84]:
t = tf.constant([[1, 1, 1], [2, 2, 2]])
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [86]:
#change the dtype- here called outtype

t = tf.constant([[1, 1, 1], [2, 2, 2]],)
tf.size(t,out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

# 12.Random Normal method

In [87]:
# https://www.tensorflow.org/api_docs/python/tf/random/normal
# Outputs random values from a normal distribution.
random_tensor=tf.random.normal(
    [3,2],
    mean=0.0, # this is normal distribution
    stddev=1.0, # this is normal distribution
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor) # if you see the all elements in matrix are very close to 0 showing Normal distribution

tf.Tensor(
[[ 0.2750867  -0.43862012]
 [-0.14218335  0.40876484]
 [-0.75498474 -0.90786606]], shape=(3, 2), dtype=float32)


In [88]:
random_tensor=tf.random.normal(
    [3,2],
    mean=100, # this is normal distribution
    stddev=1.0, # this is normal distribution
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor) # if you see the all elements in matrix are far away from 0 close to 100 showing No Normal distribution

tf.Tensor(
[[ 99.73101  100.62563 ]
 [ 99.619644  99.33961 ]
 [ 98.33884   99.67424 ]], shape=(3, 2), dtype=float32)


# 11. Uniform method

In [91]:
# https://www.tensorflow.org/api_docs/python/tf/random/uniform
random_tensor=tf.random.uniform(
    [5,],
    minval=0,
    maxval=8,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor([0.7093086 4.782407  7.717207  2.840849  6.352215 ], shape=(5,), dtype=float32)


In [93]:
random_tensor=tf.random.uniform(
    [1,],
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor([0.56499684], shape=(1,), dtype=float32)


In [98]:
random_tensor=tf.random.uniform(
    [2,2],
    minval=0,
    maxval=100,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[26 84]
 [13 40]], shape=(2, 2), dtype=int32)


In [96]:
random_tensor=tf.random.uniform(
    [5,5],
    minval=0,
    maxval=1000,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[496 325 831 556 989]
 [739 259 458 535 676]
 [834  47 821 652 525]
 [274 976 109 556 768]
 [372 863 663 649 241]], shape=(5, 5), dtype=int32)


# 12.RandomSeed

In [99]:
# https://www.tensorflow.org/api_docs/python/tf/random/set_seed

tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))




tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)
tf.Tensor([4 2 2], shape=(3,), dtype=int32)


In [100]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))



tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)
tf.Tensor([4 2 2], shape=(3,), dtype=int32)


* See that since seed is set to 10  even the though the random method is used we are able to reproduce the same result

In [101]:
# change seed and see results change s

tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=1)) # i changed this


tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)
tf.Tensor([4 1 3], shape=(3,), dtype=int32)


In [102]:
# change seed and see results change s

tf.random.set_seed(2) # now i changed this
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=1)) # i changed this

tf.Tensor([1 2 1], shape=(3,), dtype=int32)
tf.Tensor([2 2 2], shape=(3,), dtype=int32)
tf.Tensor([4 0 1], shape=(3,), dtype=int32)
tf.Tensor([3 2 1], shape=(3,), dtype=int32)
tf.Tensor([4 2 0], shape=(3,), dtype=int32)


In [104]:
# change seed and see results change s

tf.random.set_seed(5) # now i change it back to 5 to see reproducebility
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)
tf.Tensor([4 2 2], shape=(3,), dtype=int32)


# 12. Tensor Index

#### 1 D tensor Indexing

In [105]:
tensor_indexed= tf.constant([2,3,4,9,9,2,4,7])

In [106]:
print(tensor_indexed[3])

tf.Tensor(9, shape=(), dtype=int32)


In [107]:
#first  element
print(tensor_indexed[0])

tf.Tensor(2, shape=(), dtype=int32)


In [108]:
#last element
print(tensor_indexed[-1])

tf.Tensor(7, shape=(), dtype=int32)


In [112]:
# just get a segment of the tensor
print(tensor_indexed[1:7])

tf.Tensor([3 4 9 9 2 4], shape=(6,), dtype=int32)


In [114]:
# just get a segment of the tensor
print(tensor_indexed[0:3])

tf.Tensor([2 3 4], shape=(3,), dtype=int32)


In [115]:
# just get a segment of the tensor
print(tensor_indexed[3:])

tf.Tensor([9 9 2 4 7], shape=(5,), dtype=int32)


In [121]:
print(tensor_indexed)
print(tensor_indexed[0:5])
print(tensor_indexed[:5:2])

tf.Tensor([2 3 4 9 9 2 4 7], shape=(8,), dtype=int32)
tf.Tensor([2 3 4 9 9], shape=(5,), dtype=int32)
tf.Tensor([2 4 9], shape=(3,), dtype=int32)


In [119]:
# just get a segment of the tensor
print(tensor_indexed[:5:2])

tf.Tensor([2 4 9], shape=(3,), dtype=int32)


#### 2D Tensor Indexing

In [137]:
tensor_indexed=tf.constant([[2,3,4,5,6],
                           [9,0,4,2,1],
                           [0,0,1,7,0]])
print(tensor_indexed)

tf.Tensor(
[[2 3 4 5 6]
 [9 0 4 2 1]
 [0 0 1 7 0]], shape=(3, 5), dtype=int32)


In [140]:
print(tensor_indexed[1,0])
print(tensor_indexed[2,2:])

tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor([1 7 0], shape=(3,), dtype=int32)
tf.Tensor(
[[6]
 [1]], shape=(2, 1), dtype=int32)
tf.Tensor(
[[6]
 [1]], shape=(2, 1), dtype=int32)


In [142]:
print(tensor_indexed[0:-1,4:]) # same thing


tf.Tensor(
[[6]
 [1]], shape=(2, 1), dtype=int32)


In [144]:
tensor_indexed[0:2,-1:]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[6],
       [1]], dtype=int32)>

In [145]:
print(tensor_indexed)

tf.Tensor(
[[2 3 4 5 6]
 [9 0 4 2 1]
 [0 0 1 7 0]], shape=(3, 5), dtype=int32)


In [147]:
tensor_indexed[:,-1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([6, 1, 0], dtype=int32)>

In [149]:
tensor_indexed[:1,:]

<tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[2, 3, 4, 5, 6]], dtype=int32)>

In [153]:
# 3 dots pull all columns
tensor_indexed[0,...]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6], dtype=int32)>

In [154]:
# 3 dots pull all columns
tensor_indexed[0:1,...]

<tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[2, 3, 4, 5, 6]], dtype=int32)>

In [155]:
print(tensor_indexed)

tf.Tensor(
[[2 3 4 5 6]
 [9 0 4 2 1]
 [0 0 1 7 0]], shape=(3, 5), dtype=int32)


In [156]:
tensor_indexed[0:2,2:-1]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 5],
       [4, 2]], dtype=int32)>

#### 3 D tensor Indexing

In [157]:
tensor_indexed = tf.constant(
                              [[[1,2,0],
                                [3,5,-1]],  #

                              [[10,2,0],
                               [1,0,2]],

                              [[5,8,0],
                               [2,7,0]],

                              [[2,1,9],
                               [4,-3,32]]]) # 4 stacked 3 d tensors

In [158]:
print(tensor_indexed) # 4 blocks of 3 d tensors

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [164]:
tensor_indexed[3,0,-1]
# tensor_indexed[3,0,2] ## same thing

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [168]:
tensor_indexed[3,0,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 1, 9], dtype=int32)>

In [170]:
tensor_indexed[3,0:2,0:-1]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  1],
       [ 4, -3]], dtype=int32)>

In [172]:
# from all block pick 3rd element
tensor_indexed[...,:,-1]
# tensor_indexed[:,:,-1]  ## same thing

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 0, -1],
       [ 0,  2],
       [ 0,  0],
       [ 9, 32]], dtype=int32)>

# 13. Tensorflow math

#### 1. Abs Method

* Given a tensor of integer or floating-point values, this operation returns a tensor of the same type, where each element contains the absolute value of the corresponding element in the input.

In [175]:
# https://www.tensorflow.org/api_docs/python/tf/random/set_seed

x=tf.constant(0.2)
print(x)

tf.Tensor(0.2, shape=(), dtype=float32)


In [176]:
x=tf.constant(-0.2)
print(x)


tf.Tensor(-0.2, shape=(), dtype=float32)


In [179]:
# using absolute method
x= tf.constant([2,-1,3,0.1,0])
print(tf.abs(x)) # it makes all -ve values positive

tf.Tensor([2.  1.  3.  0.1 0. ], shape=(5,), dtype=float32)


In [180]:
# using absolute method
x= tf.constant([2,-1,3,-0.1,0])
print(tf.abs(x)) # it makes all -ve values positive

tf.Tensor([2.  1.  3.  0.1 0. ], shape=(5,), dtype=float32)


Given a tensor x of complex numbers, this operation returns a tensor of type float32 or float64 that is the absolute value of each element in x. For a complex number a+bj
, its absolute value is computed as sqrt(a^2 +b^2)


In [181]:
# using absolute method
x= tf.constant(2+3j)
print(tf.abs(x)) # it makes all -ve values positive

tf.Tensor(3.605551275463989, shape=(), dtype=float64)


In [185]:
# checking if the correct abs value
tf.sqrt(2.0**2+3.0**2)

<tf.Tensor: shape=(), dtype=float32, numpy=3.605551242828369>

* Answer is correct

#### 2. Add Method

* the function will add matrixes even when the shape is different

In [187]:
x=tf.constant([2,3,5,7])
y=tf.constant([7,7,2,1])
tf.add(x,y)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 9, 10,  7,  8], dtype=int32)>

In [188]:
x=tf.constant([2,3,5,7])
y=tf.constant(1)
tf.add(x,y)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 4, 6, 8], dtype=int32)>

#### 2.  Subtraction and Division example are present on documentation:  

In [189]:
# https://www.tensorflow.org/api_docs/python/tf/math/add
# https://www.tensorflow.org/api_docs/python/tf/math/subtract
# https://www.tensorflow.org/api_docs/python/tf/math/multiply
# https://www.tensorflow.org/api_docs/python/tf/math/divide


#### 3. divide_no_nan Method

*  Computes a safe divide which returns 0 if y (denominator) is zero.

In [190]:
x=tf.constant([2,3,5,7])
y=tf.constant(0)
tf.math.divide_no_nan(x,y) # safety net to aviod infinity

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0., 0., 0., 0.])>

In [193]:
x=tf.constant([2,3,5,7])
y=tf.constant([0,2,4,5])

#observe  the out puts for this and see infinity
print(tf.math.divide_no_nan(x,y))
print(tf.math.divide(x,y))


tf.Tensor([0.   1.5  1.25 1.4 ], shape=(4,), dtype=float64)
tf.Tensor([ inf 1.5  1.25 1.4 ], shape=(4,), dtype=float64)


#### 4. multiply Method

In [195]:
x=tf.constant([[2,3,4,5]])
y=tf.constant([[1],
              [3]])

print(tf.math.multiply(x,y))

tf.Tensor(
[[ 2  3  4  5]
 [ 6  9 12 15]], shape=(2, 4), dtype=int32)


#### 5. maximum and minimum Method

In [196]:
# https://www.tensorflow.org/api_docs/python/tf/math/maximum
# https://www.tensorflow.org/api_docs/python/tf/math/minimum

x = tf.constant([0., 0., 0., 0.])
y = tf.constant([-2., 0., 2., 5.])
tf.math.maximum(x, y) # return max after comparing element wise

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 2., 5.], dtype=float32)>

In [197]:
x = tf.constant([-5., 0., 0., 0.])
y = tf.constant([-3.])
tf.math.maximum(x, y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-3.,  0.,  0.,  0.], dtype=float32)>

In [198]:
x = tf.constant([0., 0., 0., 0.])
y = tf.constant([-5., -2., 0., 3.])
tf.math.minimum(x, y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-5., -2.,  0.,  0.], dtype=float32)>

In [199]:
x = tf.constant([-5., 0., 0., 0.])
y = tf.constant([-3.])
tf.math.minimum(x, y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-5., -3., -3., -3.], dtype=float32)>

#### 5. Arg max  Method
* Returns the index with the largest value across axes of a tensor.

In [200]:
# https://www.tensorflow.org/api_docs/python/tf/math/argmax
# https://www.tensorflow.org/api_docs/python/tf/math/argmin

In [201]:
A = tf.constant([2,20,30,3,6])
tf.math.argmax(A) # index 2 means 30

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [202]:
A = tf.constant([2,20,30,3,6])
tf.math.argmin(A) # index 0 means 0

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [211]:
# if you have 2 d tensors
t_argmax = tf.constant(
  [[3,1,9,6,5],
  [0,1,7,3,2],
  [1,5,1,2,0],
  [7,3,0,9,0],]
)
tf.math.argmax(t_argmax) # indexes of hight elements are fetched

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([3, 2, 0, 3, 0])>

In [205]:
# if you have 2 d tensors
t_argmin = tf.constant(
  [[3,1,9,6,5],
  [0,1,7,3,2],
  [1,5,1,2,0],
  [7,3,0,9,0],]
)
tf.math.argmin(t_argmin) # indexes of lowest elements are fetched

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 0, 3, 2, 2])>

In [210]:
# if you have 2 d tensors change axis
t_argmax = tf.constant([
  [3,1,9,6,5],
  [0,1,7,3,2],
  [1,5,1,2,0],
  [7,3,0,9,0],

])
tf.math.argmax(t_argmax,axis=1) # indexes of highest elements are fetched column wise

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([2, 2, 1, 3])>

In [212]:
# if you have 2 d tensors change axis
t_argmin= tf.constant([
  [3,1,9,6,5],
  [0,1,7,3,2],
  [1,5,1,2,0],
  [7,3,0,9,0],

])
tf.math.argmin(t_argmin,axis=1) # indexes of highest elements are fetched column wise

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 0, 4, 2])>

#### 6. Equal  Method

In [ ]:
# https://www.tensorflow.org/api_docs/python/tf/math/equal